USE teste_engsoftware;

INSERT INTO products (name, image, description, brand, category, price, countInStock, rating, numReviews) VALUES
('Semáforo em Arduino', '/images/semaforo.png', 'Projeto para disciplina de Introdução à Engenharia Elétrica.', 'Fabricação própria', 'Eletrônicos', 100.00, 0, 5, 1),
('Kit 500 Resistores Variados de 20Ω a 1MΩ', '/images/kitresistor.png', 'Kit de resistores variados, útil em diversas disciplinas de laboratório ao longo do curso.', '-', 'Eletrônicos', 30.00, 10, 4.9, 45),
('Kit Rasberry PI 4 Advanced', '/images/raspberry.png', 'O Kit Raspberry Pi Advanced é ideal para iniciantes e inclui a placa Raspberry Pi 4 Model B (4GB), cabo HDMI, case, dissipador, cartão de memória e fonte. Ele permite criar projetos de automação residencial, emuladores de videogames, IoT e mais. A Raspberry Pi 4 Model B apresenta um processador quad-core 64-bit de 1.5 GHz, portas USB 3.0, suporte a PoE, WiFi de 2.4GHz e 5GHz, Bluetooth 5.0 e a capacidade de usar dois monitores simultaneamente.', 'Raspberry PI Foundation', 'Eletrônicos', 600.00, 1, 4.9, 10),
('Motor DC', '/images/motordc.png', 'Projeto desenvolvido para a disciplina de Laboratório de Conversão da Energia em que é pedido um motor que funcione em corrente contínua.', 'Fabricação própria', 'Projetos', 100.00, 1, 4.8, 5),
('Placa Fenolite Perfurada 12x18cm', '/images/placapcb.png', 'Placa de circuito impresso ilhada (Wire-Wrap) em fenolite, ideal para fixar definitivamente componentes eletrônicos  sem a necessidade de confeccionar uma placa desde o início. Não é necessário o uso de percloreto para corrosão e já vem furada para encaixar os terminais. Basta colocar os componentes e soldar. Útil para Laboratório de Sistemas de Medição.', '-', 'Eletrônicos', 5.00, 5, 3, 7),
('Kit Arduino Master', '/images/arduino.png', 'Com este kit, você aprenderá a criar diversos projetos eletrônicos práticos, como leitura de sinais analógicos com potenciômetro, controle de LEDs e servo motor, medição de temperatura e umidade, e desenvolvimento de um cronômetro digital. Também inclui projetos como trena eletrônica com sensor ultrassônico, irrigação automática com sensores, leitura de cartões RFID e um relógio digital de alta precisão. Essa experiência oferece uma sólida compreensão de conceitos eletrônicos fundamentais.', 'SparkFun Eletronics', 'Eletrônicos', 150.00, 2, 4.9, 2),
('Transistor NPN 2N2222', '/images/transistor.png', 'O 2N2222 é um transistor simples e de uso geral na eletrônica. É muito utilizado em aplicações de chaveamento e amplificação. Pode ser utilizada em disciplinas como Laboratório de Eletrônica 1 e Laboratório de Eletrônica 2.', '-', 'Eletrônicos', 0.25, 150, 4.5, 23),
('Robô Seguidor de Linha', '/images/robo.png', 'Esse é um projeto inicial que pode ser usado para discentes que se interessem em participar da CORA.', 'Fabricação própria', 'Eletrônicos', 150.00, 4, 4.9, 3);